export const MESSAGE = {
    NAME_ERROR: "Name should have at least 3 characters",
    EMAILID_ERROR: "Please enter a valid email",
    PASSWORD_ERROR: "Please enter a valid Password",
    CONFIRM_PASSWORD_ERROR: "Password didn't match",
    MANDATORY: "Please fill all the fields",
    ADDRESS_ERROR: "Address/City cann't be empty",
    PIN_CODE_ERROR: "Pin Code must be 6 digit",
  };

export const STATES = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    " Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
  ];